# Generated by Django 2.2 on 2020-10-27 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logourl', models.ImageField(blank=True, max_length=255, null=True, upload_to='logos/%Y/%m/%d/')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('imageurl', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/%Y/%m/%d/')),
                ('price', models.FloatField()),
                ('reorderqty', models.IntegerField()),
                ('stockavailable', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('brandid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prods', to='productapp.Brand')),
            ],
        ),
    ]
